<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(BaseTargetFramework)</TargetFramework>
        <RootNamespace>Shiny</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="UXDivers.Popups.Maui" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shiny.Maui.Core\Shiny.Maui.Core.csproj" />
    </ItemGroup>

</Project>
