<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(BaseTargetFramework);$(BaseTargetFramework)-android;$(BaseTargetFramework)-ios;$(BaseTargetFramework)-maccatalyst</TargetFrameworks>
        <TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);$(BaseTargetFramework)-windows10.0.19041.0</TargetFrameworks>
        <RootNamespace>Shiny</RootNamespace>
        <EnableDefaultMauiMacCatalystTarget>false</EnableDefaultMauiMacCatalystTarget>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Maui.Controls" />
        <ProjectReference Include="..\Shiny.Maui.Core\Shiny.Maui.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\Shiny.Maui.Shell.SourceGenerators\build\Package.targets"
              Pack="True"
              PackagePath="build/Shiny.Maui.Shell.targets" />

        <None Include="..\Shiny.Maui.Shell.SourceGenerators\build\Package.targets"
              Pack="True"
              PackagePath="buildTransitive/Shiny.Maui.Shell.targets" />
    
        <None Include="..\Shiny.Maui.Shell.SourceGenerators\bin\$(Configuration)\netstandard2.0\Shiny.Maui.Shell.SourceGenerators.dll"
              Pack="true"
              PackagePath="analyzers/dotnet/cs"
              Visible="false" />
    </ItemGroup>
</Project>
