<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
        <MauiVersion>10.0.51</MauiVersion>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="Microsoft.Extensions.AI" Version="10.5.0"/>
        <PackageVersion Include="Microsoft.Extensions.AI.OpenAI" Version="10.5.0"/>
        <PackageVersion Include="Nerdbank.GitVersioning" Version="3.9.50"/>
        <PackageVersion Include="Microsoft.Maui.Controls" Version="$(MauiVersion)"/>
        <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.8.0"/>
        <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2"/>
        <PackageVersion Include="Shiny.Maui.Controls" Version="1.0.1-beta-0127"/>
        <PackageVersion Include="UXDivers.Popups.Maui" Version="0.9.4"/>
        <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.0"/>
    </ItemGroup>
    <ItemGroup>
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.4.0"/>
        <PackageVersion Include="MartinCostello.Logging.XUnit" Version="0.7.0"/>
        <PackageVersion Include="Shouldly" Version="4.3.0"/>
        <PackageVersion Include="Verify.SourceGenerators" Version="2.5.0"/>
        <PackageVersion Include="Verify.Xunit" Version="31.12.5"/>
        <PackageVersion Include="xunit" Version="2.9.3"/>
        <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5"/>
    </ItemGroup>
</Project>