<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>$(BaseTargetFramework)</TargetFramework>
        <RootNamespace>Shiny</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Shiny.Maui.Controls" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shiny.Maui.Shell\Shiny.Maui.Shell.csproj" />
    </ItemGroup>

</Project>
